### ISSUE TITLE
System.EntryPointNotFoundException when running generated C# code.

### ISSUE THREAD

**Issue by dennisai** [mono/CppSharp#1058]
I am trying to wrap the [ome-files](https://www.openmicroscopy.org/ome-files/downloads/) library, and am running into a `System.EntryPointNotFoundException` exception when I try to use the generated code from CppSharp.  In order to do this, I have done the following.

1. Download the [ome-files](https://www.openmicroscopy.org/ome-files/downloads/) distribution for Windows VC14 64‑bit (VS2015).
2. Create a C++ library in Visual Studio (.dll, targeting Windows 10.0.14393.0) that interfaces with only the parts of the API that I am interested in (e.g. OMETIFFReader.h, OMETIFFWriter.h, etc.).
3. Generate the C# wrapper using CppSharp, and import the .cs files into a C# project in Visual Studio and compile that.
4. Include the library from 3 into a project with unit tests, and run `OMETIFFReader reader = new OMETIFFReader();`.  I have included the .dll from the library I created in Step 2, and all the .dlls from the ome-files distribution downloaded in Step 1.

This results in the following error.  Any idea why we can't seem to find an entry point?

```
Result StackTrace:	
at OME.IO.OMETIFFReader.__Internal.ctor(IntPtr instance)
   at OME.IO.OMETIFFReader..ctor() in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp\IO\OMEFiles.cs:line 209
   at OME.IO.UnitTests.OMETIFFReaderUnitTests.Open_OMETIFFFile_DoesNotThrowException() in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp.UnitTests\IO\UnitTests\OMETIFFReaderUnitTests.cs:line 41
Result Message:	System.EntryPointNotFoundException : Unable to find an entry point named '??0OMETIFFReader@@QEAA@XZ' in DLL 'OMEFiles'.
```

The only settings I set in my `OMEFilesLibrary.cs` file are:

```
driverOptions.GeneratorKind = GeneratorKind.CSharp;
driverOptions.OutputDir = outputDirectoryPath;
driverOptions.Verbose = true;
```

Here's the verbose results from running the generator.

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0
Parsing libraries...
Parsed 'OMEFiles.lib'
Parsing code...
Parsed 'OMETIFFReader.h'
Parsed 'OMETIFFWriter.h'
Parsed 'PixelBuffer.h'
Processing code...
Pass 'CppSharp.Passes.SortDeclarationsPass'
Pass 'CppSharp.Passes.ResolveIncompleteDeclsPass'
Pass 'CppSharp.Passes.IgnoreSystemDeclarationsPass'
Pass 'CppSharp.Passes.EqualiseAccessOfOverrideAndBasePass'
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Decl 'reader' was ignored due to invalid access
    Field 'OMETIFFReader::reader' was ignored due to ignored type '::std::unique_ptr<::ome::files::in::OMETIFFReader, ::std::default_delete<::ome::files::in::OMETIFFReader>>'
    Decl '_First' was ignored due to invalid access
    Decl '_Last' was ignored due to invalid access
    Decl '_First' was ignored due to invalid access
    Decl '_Last' was ignored due to invalid access
    Function 'allocator' was ignored due to ignored param
    Function 'allocator<_Ty>' was ignored due to ignored param
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Field '_Compressed_pair::_Myval2' was ignored due to ignored type '::std::_String_val<::std::_Simple_types<char>>'
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type ''
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::VariantPixelBuffer>, ::ome::files::VariantPixelBuffer*>'
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::in::OMETIFFReader>, ::ome::files::in::OMETIFFReader*>'
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::out::OMETIFFWriter>, ::ome::files::out::OMETIFFWriter*>'
    Typedef 'type' was ignored due to ignored type
    Typedef 'type' was ignored due to ignored type
    Typedef 'type' was ignored due to ignored type
    Field '_String_val::_Bx' was ignored due to ignored type '::std::_String_val<::std::_Simple_types<char>>::_Bxty'
    Decl '_Mypair' was ignored due to invalid access
    Field '_String_alloc::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::allocator<char>, ::std::_String_val<::std::_Simple_types<char>>>'
    Decl '_Mypair' was ignored due to invalid access
    Field '_String_alloc::_Mypair' was ignored due to ignored type ''
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Field '_String_val::_Bx' was ignored due to ignored type '::std::_String_val::_Bxty'
    Decl 'buffer' was ignored due to invalid access
    Field 'PixelBuffer::buffer' was ignored due to ignored type '::std::unique_ptr<::ome::files::VariantPixelBuffer, ::std::default_delete<::ome::files::VariantPixelBuffer>>'
    Decl 'writer' was ignored due to invalid access
    Field 'OMETIFFWriter::writer' was ignored due to ignored type '::std::unique_ptr<::ome::files::out::OMETIFFWriter, ::std::default_delete<::ome::files::out::OMETIFFWriter>>'
Pass 'CppSharp.Passes.GenerateSymbolsPass'
Pass 'CppSharp.Passes.TrimSpecializationsPass'
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Decl 'reader' was ignored due to invalid access
    Field 'OMETIFFReader::reader' was ignored due to internal type '::std::unique_ptr<::ome::files::in::OMETIFFReader, ::std::default_delete<::ome::files::in::OMETIFFReader>>'
    Decl '_First' was ignored due to invalid access
    Decl '_Last' was ignored due to invalid access
    Decl '_First' was ignored due to invalid access
    Decl '_Last' was ignored due to invalid access
    Function 'allocator' was ignored due to ignored param
    Function 'allocator<_Ty>' was ignored due to ignored param
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Field '_Compressed_pair::_Myval2' was ignored due to internal type '::std::_String_val<::std::_Simple_types<char>>'
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type ''
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::VariantPixelBuffer>, ::ome::files::VariantPixelBuffer*>'
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::in::OMETIFFReader>, ::ome::files::in::OMETIFFReader*>'
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::out::OMETIFFWriter>, ::ome::files::out::OMETIFFWriter*>'
    Typedef 'type' was ignored due to ignored type
    Typedef 'type' was ignored due to ignored type
    Typedef 'type' was ignored due to ignored type
    Field '_String_val::_Bx' was ignored due to internal type '::std::_String_val<::std::_Simple_types<char>>::_Bxty'
    Decl '_Mypair' was ignored due to invalid access
    Field '_String_alloc::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::allocator<char>, ::std::_String_val<::std::_Simple_types<char>>>'
    Decl '_Mypair' was ignored due to invalid access
    Field '_String_alloc::_Mypair' was ignored due to ignored type ''
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Field '_String_val::_Bx' was ignored due to ignored type '::std::_String_val::_Bxty'
    Decl 'buffer' was ignored due to invalid access
    Field 'PixelBuffer::buffer' was ignored due to ignored type '::std::unique_ptr<::ome::files::VariantPixelBuffer, ::std::default_delete<::ome::files::VariantPixelBuffer>>'
    Decl 'writer' was ignored due to invalid access
    Field 'OMETIFFWriter::writer' was ignored due to ignored type '::std::unique_ptr<::ome::files::out::OMETIFFWriter, ::std::default_delete<::ome::files::out::OMETIFFWriter>>'
Pass 'CppSharp.Passes.FindSymbolsPass'
Pass 'CppSharp.Passes.CheckMacroPass'
Pass 'CppSharp.Passes.CheckStaticClass'
Pass 'CppSharp.Passes.MoveOperatorToClassPass'
Pass 'CppSharp.Passes.MoveFunctionToClassPass'
Pass 'CppSharp.Passes.ConstructorToConversionOperatorPass'
Pass 'CppSharp.Passes.MarshalPrimitivePointersAsRefTypePass'
Pass 'CppSharp.Passes.CheckAmbiguousFunctions'
Pass 'CppSharp.Passes.CheckOperatorsOverloadsPass'
    Invalid operator overload OMETIFFReader::Equal
    Invalid operator overload PixelBuffer::Equal
    Invalid operator overload OMETIFFWriter::Equal
Pass 'CppSharp.Passes.CheckVirtualOverrideReturnCovariance'
Pass 'CppSharp.Passes.CleanCommentsPass'
Pass 'CppSharp.Passes.CheckAbiParameters'
Pass 'CppSharp.Passes.FieldToPropertyPass'
    Property created from field: std::_String_val<global::std._Simple_types<sbyte>>::_Bxty::___Buf
    Property created from field: std::_String_val<global::std._Simple_types<sbyte>>::_Bxty::___Ptr
    Property created from field: std::_String_val<global::std._Simple_types<sbyte>>::_Bxty::___Alias
    Property created from field: std::_String_val::_Bxty::___Buf
    Property created from field: std::_String_val::_Bxty::___Ptr
    Property created from field: std::_String_val::_Bxty::___Alias
Pass 'CppSharp.Passes.CleanInvalidDeclNamesPass'
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Decl 'reader' was ignored due to invalid access
    Field 'OMETIFFReader::reader' was ignored due to ignored type '::std::unique_ptr<::ome::files::in::OMETIFFReader, ::std::default_delete<::ome::files::in::OMETIFFReader>>'
    Function 'operator=' was ignored due to ignored param
    Decl '_First' was ignored due to invalid access
    Decl '_Last' was ignored due to invalid access
    Decl '_First' was ignored due to invalid access
    Decl '_Last' was ignored due to invalid access
    Function 'allocator' was ignored due to ignored param
    Function 'allocator<_Ty>' was ignored due to ignored param
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Field '_Compressed_pair::_Myval2' was ignored due to ignored type '::std::_String_val<::std::_Simple_types<char>>'
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Decl '_Myval2' was ignored due to invalid access
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type ''
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::VariantPixelBuffer>, ::ome::files::VariantPixelBuffer*>'
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::in::OMETIFFReader>, ::ome::files::in::OMETIFFReader*>'
    Typedef 'pointer' was ignored due to ignored type
    Field '_Unique_ptr_base::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::default_delete<::ome::files::out::OMETIFFWriter>, ::ome::files::out::OMETIFFWriter*>'
    Typedef 'type' was ignored due to ignored type
    Typedef 'type' was ignored due to ignored type
    Typedef 'type' was ignored due to ignored type
    Property '_Buf' was ignored due to ignored decl
    Property '_Ptr' was ignored due to ignored decl
    Property '_Alias' was ignored due to ignored decl
    Field '_String_val::_Bx' was ignored due to ignored type '::std::_String_val<::std::_Simple_types<char>>::_Bxty'
    Decl '_Mypair' was ignored due to invalid access
    Field '_String_alloc::_Mypair' was ignored due to ignored type '::std::_Compressed_pair<::std::allocator<char>, ::std::_String_val<::std::_Simple_types<char>>>'
    Decl '_Mypair' was ignored due to invalid access
    Field '_String_alloc::_Mypair' was ignored due to ignored type ''
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string<_Elem, _Traits, _Alloc>' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Function 'basic_string' was ignored due to ignored param
    Property '_Buf' was ignored due to ignored decl
    Property '_Ptr' was ignored due to ignored decl
    Property '_Alias' was ignored due to ignored decl
    Field '_String_val::_Bx' was ignored due to ignored type '::std::_String_val::_Bxty'
    Decl 'buffer' was ignored due to invalid access
    Field 'PixelBuffer::buffer' was ignored due to ignored type '::std::unique_ptr<::ome::files::VariantPixelBuffer, ::std::default_delete<::ome::files::VariantPixelBuffer>>'
    Function 'operator=' was ignored due to ignored param
    Decl 'writer' was ignored due to invalid access
    Field 'OMETIFFWriter::writer' was ignored due to ignored type '::std::unique_ptr<::ome::files::out::OMETIFFWriter, ::std::default_delete<::ome::files::out::OMETIFFWriter>>'
    Function 'operator=' was ignored due to ignored param
Pass 'CppSharp.Passes.CheckFlagEnumsPass'
Pass 'CppSharp.Passes.CheckDuplicatedNamesPass'
Pass 'CppSharp.Passes.GenerateAbstractImplementationsPass'
Pass 'CppSharp.Passes.MultipleInheritancePass'
Pass 'CppSharp.Passes.DelegatesPass'
Pass 'CppSharp.Passes.GetterSetterToPropertyPass'
Pass 'CppSharp.Passes.StripUnusedSystemTypesPass'
Pass 'CppSharp.Passes.SpecializationMethodsWithDependentPointersPass'
Pass 'CppSharp.Passes.ParamTypeToInterfacePass'
Pass 'CppSharp.Passes.MarkUsedClassInternalsPass'
Pass 'CppSharp.Passes.CaseRenamePass'
Generating code...
Generated 'Std.cs'
Generated 'OMEFiles.cs'
```

**Comment by ddobrev** [comment]
@dennisai you need to compile the generated C++ for symbols. It's located along your other output. See https://gitlab.com/ddobrev/QtSharp/blob/master/QtSharp/QtSharp.cs#L221 for an example.

**Comment by dennisai** [comment]
@ddobrev thank you for the quick response.  So I see this `Std-symbols.cpp` file that was generated, is that what you are referring to?  What is the right process for compiling it on Windows?  Should I be adding it to a new C++ library?  My C# wrapper library?  I took a look at the code link you provided, but it's hard for me to understand what it's actually doing / what I need to be doing from it.

**Comment by ddobrev** [comment]
@dennisai only if you need std::string, other than that you need <your_lib>-symbols.cpp.

**Comment by dennisai** [comment]
@ddobrev I do not see a `<your_lib>-symbols.cpp` file.  I only get a `OMEFiles.cpp`, `Std.cs`, and `Std-symbols.cpp`.

This is my OMEFilesLibrary.cs class, is there a setting I am missing?

```
    public class OMEFilesLibrary : ILibrary
    {
        // Constants
        private readonly string[] OMEHeaders = new string[]
        {
            "OMETIFFReader.h",
            "OMETIFFWriter.h",
            "PixelBuffer.h"
        };

        // Fields
        private readonly string outputDirectoryPath;
        private readonly string projectDirectoryPath;

        // Constructors
        public OMEFilesLibrary(
            string projectDirectoryPath,
            string outputDirectoryPath)
        {
            this.outputDirectoryPath = outputDirectoryPath;
            this.projectDirectoryPath = projectDirectoryPath;
        }

        // Public Methods
        public void Setup(
            Driver driver)
        {
            DriverOptions driverOptions = driver.Options;
            
            driverOptions.GeneratorKind = GeneratorKind.CSharp;
            driverOptions.OutputDir = outputDirectoryPath;
            driverOptions.Verbose = true;

            GenerateModule(
                driverOptions,
                "OMEFiles",
                Path.Combine(projectDirectoryPath, "include"),
                Path.Combine(projectDirectoryPath, "lib"),
                "OMEFiles.lib",
                OMEHeaders);
        }

        public void SetupPasses(
            Driver driver)
        {
        }

        public void Preprocess(
            Driver driver,
            ASTContext ctx)
        {
            IgnoreClass(ctx, "ome::files::in::OMETIFFReader");
            IgnoreClass(ctx, "ome::files::out::OMETIFFWriter");
            IgnoreClass(ctx, "ome::files::VariantPixelBuffer");
        }

        public void Postprocess(
            Driver driver,
            ASTContext ctx)
        {

        }

        private Module GenerateModule(
            DriverOptions driverOptions,
            string moduleName,
            string includeDirectory,
            string libraryDirectory,
            string libraryFileName,
            params string[] headerFileNames)
        {
            Module module = driverOptions.AddModule(moduleName);

            module.OutputNamespace = "OME.IO";
            module.IncludeDirs.Add(includeDirectory);
            module.LibraryDirs.Add(libraryDirectory);
            module.Libraries.Add(libraryFileName);

            foreach (string headerFileName in headerFileNames)
            {
                module.Headers.Add(headerFileName);
            }

            return module;
        }

        private void IgnoreClass(
            ASTContext ctx,
            string className)
        {
            foreach (var c in ctx.FindClass(className))
            {
                c.ExplicitlyIgnore();
            }
        }
    }
```

**Comment by ddobrev** [comment]
I am afraid I have little idea why you don't get that file. I am going to get back to you as soon as I have been able to investigate this one.

**Comment by tritao** [comment]
You don't need any complication with external symbols libraries. Just make sure to add `__declspec(dllexport)` to your wrapper C++ code and recompile.

**Comment by dennisai** [comment]
@tritao thank you, it looked like that seemed to fix the current issue.  However, now I get the exception:

```
Result StackTrace:	at OME.IO.UnitTests.OMETIFFReaderUnitTests.Open_OMETIFFFile_DoesNotThrowException() in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp.UnitTests\IO\UnitTests\OMETIFFReaderUnitTests.cs:line 42
Result Message:	
Expected: No Exception to be thrown
  But was:  <System.DllNotFoundException: Unable to load DLL 'Std-symbols': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Std.Allocator.__Internal.ctorc__N_std_S_allocator__C(IntPtr instance)
   at Std.Allocator`1..ctor() in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp\IO\Std.cs:line 159
   at OME.IO.OMETIFFReader.Open(String filepath) in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp\IO\OMEFiles.cs:line 241
   at OME.IO.UnitTests.OMETIFFReaderUnitTests.<>c__DisplayClass2_0.<Open_OMETIFFFile_DoesNotThrowException>b__0() in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp.UnitTests\IO\UnitTests\OMETIFFReaderUnitTests.cs:line 42
   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
```

My 'Std-symbols.cpp' class looks like the following.

```
#include <string>

template class __declspec(dllexport) std::char_traits<char>;
template class __declspec(dllexport) std::allocator<char>;
template class __declspec(dllexport) std::basic_string<char, std::char_traits<char>, std::allocator<char>>;
```

If I put the `Std-symbols.cpp` into its own project and compile into a DLL, and drop the DLL in, I get the following.

```
Result StackTrace:	at OME.IO.UnitTests.OMETIFFReaderUnitTests.Open_OMETIFFFile_DoesNotThrowException() in C:\Users\...Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp.UnitTests\IO\UnitTests\OMETIFFReaderUnitTests.cs:line 42
Result Message:	
Expected: No Exception to be thrown
  But was:  <System.EntryPointNotFoundException: Unable to find an entry point named '?' in DLL 'Std-symbols'.
   at Std.BasicStringExtensions.__Internal.BasicString(IntPtr instance, String _Ptr, IntPtr _Al)
   at Std.BasicStringExtensions.BasicString(String _Ptr, Allocator`1 _Al) in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp\IO\Std.cs:line 236
   at OME.IO.OMETIFFReader.Open(String filepath) in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp\IO\OMEFiles.cs:line 242
   at OME.IO.UnitTests.OMETIFFReaderUnitTests.<>c__DisplayClass2_0.<Open_OMETIFFFile_DoesNotThrowException>b__0() in C:\Users\...\Documents\Visual Studio 2015\Projects\OMEFilesSharp\OMEFilesSharp.UnitTests\IO\UnitTests\OMETIFFReaderUnitTests.cs:line 42
   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
```

**Comment by tritao** [comment]
Are you using any C++ standard library types on your interface?

Just simplify and use C types, then you will not need any extra generated `Std-symbols`.

**Comment by dennisai** [comment]
@tritao yes I am using `std::size_t`, which I supposed I could replace with an `int` or `uint` for my purposes.  However, what's the best way to replace `const std::string&` for both return types and for function parameters?  Right now I have two cases (examples below):

`void open(const std::string& filepath);`
`const std::string& getDimensionOrder();`

Some Googling turns up options like returning `const char *`?  Will CppSharp be able to parse that correctly into a string?  What's the best type to use in each of the above cases?  Sorry for the obvious question.

**Comment by tritao** [comment]
`size_t` is fine, the problem is `std::string`. Either you compile the extra `Std-symbols` or replace it with `const char *`.

**Comment by pvchandu** [comment]
Hello, 

I am also facing the same issue.
I generated the binding files using cppsharp. 

I included the generated .cs and symbols file in my C# application to call the C++ methods.
But the call is failing with the error that "Entry point  not found".

Here is what I debugged:

1. I used the Dependency Walker software to see the name of the functions that the C++ dll has.
2. The dll did not have my C++ functions.
3. The symbols file only has the class name. It did not have my C++ function name in the symbols file.

4. I added the extern in my C++ header file.

extern "C" class ArithmeticFunctions
{
    public:
        _declspec(dllexport) double Add(double arg1, double arg2);
        _declspec(dllexport) double Subtract(double arg1, double arg2);
        _declspec(dllexport) double Multiply(double arg1, double arg2);
        _declspec(dllexport) double Divide(double arg1, double arg2);
};

5. Here is the symbols that I printed out using the code.

Code: 

foreach (var symbol in driver.Context.Symbols.Symbols)
            {
                Console.WriteLine(symbol.Key);
                Console.WriteLine(symbol.Value);
            }

Symbols:

?Add@ArithmeticFunctions@@QAENNN@Z
CppSharp.AST.NativeLibrary
?Divide@ArithmeticFunctions@@QAENNN@Z
CppSharp.AST.NativeLibrary
?Multiply@ArithmeticFunctions@@QAENNN@Z
CppSharp.AST.NativeLibrary
?Subtract@ArithmeticFunctions@@QAENNN@Z
CppSharp.AST.NativeLibrary

5. I used the Dependency Walker software to see the name of the functions that this new C++ dll has, and it matches with the above symbols.

6. When I looked at the generated .cs file, I see the below.

           [SuppressUnmanagedCodeSecurity]
            [DllImport("ArithmeticLibrary", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
           EntryPoint="?Add@ArithmeticFunctions@@QEAANNN@Z")]
           internal static extern double Add(global::System.IntPtr __instance, double arg1, double arg2);

As you can see the EntryPoint defined in the .cs does not match the function name generated by the C++ dll.

Hence my C# code is failing to find the Entry point.

7. When I chanaged the code in the .cs as follows, my C# code succeeds.

            [SuppressUnmanagedCodeSecurity]
            [DllImport(@"C:\Users\vipulpa\OneDrive - Microsoft\Surface(E-Drive)\CrossPlatformApps\Sample\ArithmeticLibrary\Debug\ArithmeticLibrary.dll", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall,
                EntryPoint= "?Add@ArithmeticFunctions@@QAENNN@Z")]

  Please note that I changed the below:
  1. The entry point generated in the .cs file
  2. Changed the Calling Convention to This Call.
  3. Changed the DllImport to refer to the original C++ generated dll, not the dll generated by the generator.
      The dll generated by the generator did not have those function names, when I saw it in the Dependency Walker software.

My understanding is that the cppSharp framework should do all this by default, and I do not have to change any of the generated files. Also, the C++ code is provided to us, and we cannot change the code, i.e. cannot add Extern statement like I did as part of my debug. My understanding is taht the cppSharp generates the symbols
[Sample.zip](https://github.com/mono/CppSharp/files/5003432/Sample.zip)

 files, that I include in my C# application and everything would work. 

Can you please help me solve these issues. I am attaching the code as well. The solution is in the folder: Sample\ArithmeticLibrary

[Sample.zip](https://github.com/mono/CppSharp/files/5003439/Sample.zip)
