### ISSUE TITLE
ArgumentNullException while parse void(*func2)(void(*bug)());

### ISSUE THREAD

**Issue by AleXr64** [mono/CppSharp#1144]
##### Brief Description
Windows 10 1803 build 17134.472
ArgumentNullException at [DelegatesPass.cs#L180](https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L180)

##### Used headers
```
struct buggy
{
	void(*func2)(void(*bug)());
};
void func2(void(*bug)());
```

##### Used settings
Master branch, x86
Target: MSVC ver 14.16.27023
WinSDK ver 10.0.17763.0
```
ILibrary.Setup()
{
            var options = driver.Options;
            driver.ParserOptions.SetupMSVC();
            options.GeneratorKind = GeneratorKind.CSharp;
            var module = options.AddModule("Buggy");
            module.IncludeDirs.Add("C:\\sdk2\\");
            module.Headers.Add("Header.h");
            options.OutputDir = "C:\\sdk2\\";
}
```
Other defaults

**Comment by AleXr64** [comment]
I made ugly [workaround](https://github.com/mono/CppSharp/compare/master...AleXr64:master), but don't know how do this better.
[Generated file](https://gist.github.com/AleXr64/2d7e71f468a4db5908b268ae9607cd50)

**Comment by AleXr64** [comment]
```
#define CS_VALUE_TYPE
struct CS_VALUE_TYPE buggy
{
	void(*func2)(void(*bug)());
};
void func2(void(*bug)());
```
[Result](https://gist.github.com/AleXr64/0b1bb91633c0f360824036629ce687ca)
Problem with type of Action<> at lines 46, 51, 64

**Comment by mwheeler** [comment]
Just confirming I too am encountering some variation of this bug, though crashing at a slightly different location within `DelegatePass`.  Due to the very similar nature of the problem, I've decided to add my report/trace to this existing ticket.

Parameter declarations whose function-pointer types are defined in-line with the parameter declarations, seem to lack a valid filename (and completely lack a valid a namespace and module - which causes issues around DelegatePass where modules and/or namespaces are assumed to always be valid/not-null).

However the suggested workaround above does not fix the issue as I encounter it.

I've encountered this just now trying to use CppSharp to generate FFmpeg bindings (where lots of structures have similar function pointers with nested function pointer type decls, eg: `AVCodecContext::execute` is `int (*execute)(struct AVCodecContext *c, int (*func)(struct AVCodecContext *c2, void *arg), void *arg2, int *ret, int count, int size)` - `func` in this case is similar to `bug` in the OPs simplified example).


Stack trace for my `AVCodecContext::execute` example:
```   at CppSharp.Passes.DelegatesPass.Match(TypedefDecl t, String delegateName, Module module) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 169
   at CppSharp.Passes.DelegatesPass.<>c__DisplayClass7_0.<GetDelegate>b__0(TypedefDecl t) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 108
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at CppSharp.Passes.DelegatesPass.GetDelegate(QualifiedType type, ITypedDecl typedDecl) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 108
   at CppSharp.Passes.DelegatesPass.CheckForDelegate(QualifiedType type, ITypedDecl decl) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 96
   at CppSharp.Passes.DelegatesPass.VisitParameterDecl(Parameter parameter) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 74
   at CppSharp.AST.Parameter.Visit[T](IDeclVisitor`1 visitor) in D:\github\CppSharp\src\AST\Function.cs:line 90
   at CppSharp.AST.AstVisitor.VisitFunctionType(FunctionType function, TypeQualifiers quals) in D:\github\CppSharp\src\AST\ASTVisitor.cs:line 104
   at CppSharp.AST.FunctionType.Visit[T](ITypeVisitor`1 visitor, TypeQualifiers quals) in D:\github\CppSharp\src\AST\Type.cs:line 272
   at CppSharp.AST.QualifiedType.Visit[T](ITypeVisitor`1 visitor) in D:\github\CppSharp\src\AST\Type.cs:line 82
   at CppSharp.AST.AstVisitor.VisitPointerType(PointerType pointer, TypeQualifiers quals) in D:\github\CppSharp\src\AST\ASTVisitor.cs:line 117
   at CppSharp.AST.PointerType.Visit[T](ITypeVisitor`1 visitor, TypeQualifiers quals) in D:\github\CppSharp\src\AST\Type.cs:line 347
   at CppSharp.AST.AstVisitor.VisitFieldDecl(Field field) in D:\github\CppSharp\src\AST\ASTVisitor.cs:line 371
   at CppSharp.AST.AstVisitor.VisitClassDecl(Class class) in D:\github\CppSharp\src\AST\ASTVisitor.cs:line 331
   at CppSharp.Passes.DelegatesPass.VisitClassDecl(Class class) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 46
   at CppSharp.AST.Class.Visit[T](IDeclVisitor`1 visitor) in D:\github\CppSharp\src\AST\Class.cs:line 314
   at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in D:\github\CppSharp\src\AST\ASTVisitor.cs:line 567
   at CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(TranslationUnit unit) in D:\github\CppSharp\src\Generator\Passes\Pass.cs:line 37
   at CppSharp.Passes.TranslationUnitPass.VisitASTContext(ASTContext context) in D:\github\CppSharp\src\Generator\Passes\Pass.cs:line 24
   at CppSharp.Passes.DelegatesPass.VisitASTContext(ASTContext context) in D:\github\CppSharp\src\Generator\Passes\DelegatesPass.cs:line 23
   at CppSharp.Generators.BindingContext.<RunPasses>b__29_0(TranslationUnitPass pass) in D:\github\CppSharp\src\Generator\BindingContext.cs:line 41
   at CppSharp.PassBuilder`1.RunPasses(Action`1 action) in D:\github\CppSharp\src\Generator\Passes\PassBuilder.cs:line 49
   at CppSharp.Generators.BindingContext.RunPasses() in D:\github\CppSharp\src\Generator\BindingContext.cs:line 35
   at CppSharp.Driver.ProcessCode() in D:\github\CppSharp\src\Generator\Driver.cs:line 285
   at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\github\CppSharp\src\Generator\Driver.cs:line 445
   at FFmpegSharp.Generator.Main(String[] args) in D:\github\CppSharp\examples\Parser\Parser.cs:line 187
```

Within the context of this stack trace, at `DelegatePass.GenerateDelegate`, the following state seems to show the problem (though I'm unsure of the cause / not familiar w/ CppSharp's codebase):

* `decl.TranslationUnit.FilePath == "<invalid>"`
* `decl.TranslationUnit.fileName == null`
* `decl.TranslationUnit.Module == null`
* `decl.TranslationUnit.Namespace == null`

**Comment by AleXr64** [comment]
> However the suggested workaround above does not fix the issue as I encounter it.

Yes, I did not find a way to fix this problem without dropping the other tests. At the moment - only crash prevention, the generated code is not valid.

**Comment by AleXr64** [comment]
![default](https://user-images.githubusercontent.com/26191634/51605744-5b749d00-1f29-11e9-9961-7af2f360ed06.png)
Looks like a clang bug...

**Comment by AleXr64** [comment]
```
#define CS_VALUE_TYPE
struct CS_VALUE_TYPE buggy
{
	void	(*func)(void(*bug)());
};
void func2(void(*not_bug)());

```

[Generated](https://gist.github.com/AleXr64/b8089a33ccc100b60fcca6177b1702a1)

**Comment by tritao** [comment]
Thanks to both of you for the reports. 
I haven't had much time to look into this yet.

@AleXr64 Does the bug only happen with `CS_VALUE_TYPE`?

**Comment by AleXr64** [comment]
> @AleXr64 Is the bug related to `CS_VALUE_TYPE`?

Nope. Even on the contrary, CS_VALUE_TYPE generates a valid one (at least without errors at the compilation level, and generally looks good).  Without CS_VALUE_TYPE - [useless code](https://gist.github.com/AleXr64/3cbeefdc59f3f7035aa3786a6e6e0dbc).

Generally, bug related to DelegatesPass. When  *bug is visited, [decl.TranslationUnit.Module](https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L107) == null

And a bit about CSharpTypePrinter.cs: [hasName is declared, but not used](https://github.com/mono/CppSharp/blob/master/src/Generator/Generators/CSharp/CSharpTypePrinter.cs#L661).

**Comment by AleXr64** [comment]
@tritao , Is it a valid behavior that fields with a type like `void (* func) ()` are ignored in FieldToPropertyPass in a normal run (not as passing by value)?

**Comment by AleXr64** [comment]
@ddobrev  i mean that case. [Generated](https://gist.github.com/AleXr64/a7e33844531be75dde04309cdfc0794b)  code does not give any public access to `func`.
```
struct buggy
{	
void(*func)();
};
```

**Comment by ddobrev** [comment]
Definitely a bug, all fields in a struct are public.

**Comment by AleXr64** [comment]
#define CS_VALUE_TYPE
```
struct FieldsPointers
{
	void(*func)();
	void (*func2)(void(*func3)());
};
struct CS_VALUE_TYPE FieldsPointersValueType
{
	void(*func)();
	void (*func2)(void(*func3)());
};
```
[Generated](https://gist.github.com/AleXr64/c03eb662b788b5aca41531af2107583d)

**Comment by AleXr64** [comment]
[System.ArgumentException](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?view=netframework-4.7.2#System_Runtime_InteropServices_Marshal_GetFunctionPointerForDelegate_System_Delegate_) at marshaling delegate. Huh...
```
struct FieldsPointers
{
	int(*FuncInt)();
};
```

**Comment by ddobrev** [comment]
@AleXr64 do you think you could make an attempt to fix this? Both @tritao and myself have been extremely busy lately so I'd rather tell you straight you'd wait for a long time relying on us, unless you try our other support options.

**Comment by AleXr64** [comment]
Yes, I try when I have time. The reason, as I understand it, is that can't marshall generics (if believe Microsoft and one Russian-language forum where the guy also tried to marshal generics). So, we need to get rid of Action <T...> and Func <T...>.

**Comment by AleXr64** [comment]
[At the moment](https://github.com/AleXr64/CppSharp/commit/228b0a3549b33ee5c7ff21ed6f90295dec793588) I have the following [result](https://gist.github.com/AleXr64/5b53ae682116d65d3da06d9ebd384cc1)

**Comment by AleXr64** [comment]
Looks like fixed by https://github.com/mono/CppSharp/commit/d735f391b18b8d8abded1f96713869c067c8e419

**Comment by AleXr64** [comment]
```
struct FieldsPointers
{
	int(*FuncInt)(int(*bug)());
};
```
Nullref at [DelegatesPass.cs#L200](https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L200)
`module == null` because `@namespase.IsValid == false`

**Comment by ddobrev** [comment]
@AleXr64 would you mind trying this one with our latest release?

**Comment by AleXr64** [comment]
@ddobrev for this header, nullref moved to [DelegatesPass.cs#L206](https://github.com/mono/CppSharp/blob/master/src/Generator/Passes/DelegatesPass.cs#L206)
```
struct FieldsPointers
{
	int(*FuncInt)(int(*bug)());
};
``` 

This header have [result](https://gist.github.com/AleXr64/c6421436263a025e81aa79cc24f02e5a)
```
struct FieldsPointers
{
	int(*FuncInt)();
};
```

**Comment by ddobrev** [comment]
Thank you @AleXr64 . I'll check it whenever I can. In case it's urgent, please contact me via my e-mail which you can find at the bottom in any of my commit messages.
