### ISSUE TITLE
Fails to load CodeDom when running on macOS

### ISSUE THREAD

**Issue by bruno-garcia** [mono/CppSharp#1554]
##### Brief Description

I'm running CLI on macOS 10.15.7 and it fails with missing `CodeDom.dll`.

Worth noting the binding C# class is actually generated. I just get the error message at the end and I'm not sure what it does after that point since I'm left with the files I need.

```
....
    Function 'sigwait' was ignored due to ignored param
    Function 'sigvec' was ignored due to ignored param
Pass 'CppSharp.Passes.CheckFlagEnumsPass'
Pass 'CppSharp.Passes.MakeProtectedNestedTypesPublicPass'
Pass 'CppSharp.Passes.GenerateAbstractImplementationsPass'
Pass 'CppSharp.Passes.MultipleInheritancePass'
Pass 'CppSharp.Passes.DelegatesPass'
Pass 'CppSharp.Passes.GetterSetterToPropertyPass'
Pass 'CppSharp.Passes.StripUnusedSystemTypesPass'
Pass 'CppSharp.Passes.SpecializationMethodsWithDependentPointersPass'
Pass 'CppSharp.Passes.ParamTypeToInterfacePass'
Pass 'CppSharp.Passes.CheckDuplicatedNamesPass'
Pass 'CppSharp.Passes.MarkUsedClassInternalsPass'
Pass 'CppSharp.Passes.CaseRenamePass'
Pass 'CppSharp.Passes.CheckKeywordNamesPass'
Pass 'CppSharp.Passes.HandleVariableInitializerPass'
Generating code...
Generated 'Std.cs'
Generated 'binding.cs'
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at CppSharp.Driver.CompileCode(Module module)
   at CppSharp.ConsoleDriver.Run(ILibrary library) in /Users/bruno/git/sentry-dotnet-native/CppSharp/CppSharp/src/Generator/Driver.cs:line 503
   at CppSharp.Generator.Run() in /Users/bruno/git/sentry-dotnet-native/CppSharp/CppSharp/src/CLI/Generator.cs:line 201
   at CppSharp.CLI.Main(String[] args) in /Users/bruno/git/sentry-dotnet-native/CppSharp/CppSharp/src/CLI/CLI.cs:line 293
```

I'm building from master (8683546) taken from your GH actions workflow:

```sh
export PLATFORM=x64
build/build.sh generate -platform $PLATFORM
build/build.sh download_llvm -platform $PLATFORM
build/build.sh restore -platform $PLATFORM
build/build.sh -platform $PLATFORM -build_only
build/test.sh -platform $PLATFORM
build/build.sh prepack -platform $PLATFORM
```

I noticed the generator project has it with `PrivateAssets=All`. Is this intentional?

https://github.com/mono/CppSharp/blob/eccd769d8b9de6970a3ab87e91c9cf3aeeeb628c/src/Generator/CppSharp.Generator.csproj#L17

It sounds like it assumes the device will have it, which might be true on Windows.
I've built locally with removing the `PrivateAssets` property and pinning to `Version=5.0.0` or 4 (there's no NuGet package version `4.0.3` as it complains to find) but truth is that I didn't get it on the output directory anyway.

**Comment by ddobrev** [comment]
CodeDom doesn't work with .NET Core. We're in the process of upgrading to compilation with Roslyn, it might be ready later today.

**Comment by tritao** [comment]
Will be fixed by https://github.com/mono/CppSharp/pull/1555.
