### ISSUE TITLE
Unable to find an entry point named (due to mangling?)

### ISSUE THREAD

**Issue by SoggyBottomBoy** [mono/CppSharp#1719]
I am trying to get familiar with how to use CppSharp and have read the documentation and some of the other examples out there. I have created a basic example (note I am no c++ developer). The generator runs fine without no errors, and I have tested this on other libraries too, however when using the generated source, I am always encountering the error:
> Unable to find an entry point named {function} in DLL {cpplibrary}

I am using the CppSharp nuget package and have kept the code as simple as possible (see github link below).
Generated code has no errors and compiles fine.

All the code can be found here:
https://github.com/SoggyBottomBoy/CppSharpExample

OS: Windows 11 / Visual Studio 2022
Target: MSVC

> System.EntryPointNotFoundException
>   HResult=0x80131523
>   Message=Unable to find an entry point named '??0Example@@QEAA@H@Z' in DLL 'CppLibrary'.
>   Source=CppSharpExampleNET
>   StackTrace:
>    at CppLibrary.Example.__Internal.ctor(IntPtr __instance, Int32 value)
>    at CppLibrary.Example..ctor(Int32 value) in D:\repos\OpenSource\CppSharpExample\CppSharpExampleNET\CppLibrary.cs:line 105
>    at Program.<Main>$(String[] args) in D:\repos\OpenSource\CppSharpExample\ConsoleAppNET\Program.cs:line 4

**Comment by SoggyBottomBoy** [comment]
Thanks that worked, I have `__declspec(dllexport)` which requires editing of the source files. Is there a more non-invasive way of exporting functions? I read .def files may be an option?

**Comment by SoggyBottomBoy** [comment]
Sorry I did not think to look at the tests, this would have been a good source to follow. This will still require me updating the source and add `DLL_API` to .h files correct?

**Comment by SoggyBottomBoy** [comment]
Thanks for your time and help, this is enough to get me started.
