### ISSUE TITLE
DllNotFoundException on Linux

### ISSUE THREAD

**Issue by goyzhang** [mono/CppSharp#1816]
##### Brief Description

I'm trying to wrap over a c++ header in a debian 11 docker container.

OS: Linux (debian 11 as devcontainer)
Include="CppSharp" Version="1.1.5.3168"

The `ConsoleDriver.Run` simply throw an exception (Even before Setup running)

```
Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in CppSharp.Parser.CSharp.dll: 'Unable to load shared library 'CppSharp.CppParser' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libCppSharp.CppParser: cannot open shared object file: No such file or directory'
   at CppSharp.Parser.CppParserOptions.__Internal.ctor(IntPtr __instance)
   at CppSharp.Parser.CppParserOptions..ctor()
   at CppSharp.Parser.ParserOptions..ctor()
   at CppSharp.Driver..ctor(DriverOptions options)
   at CppSharp.ConsoleDriver.Run(ILibrary library)
```

**Comment by thiago-bessa** [comment]
I'm having the exact same problem running in Kubuntu 20.04, with CppSharp v1.1.5.3168 and .NET SDK 6.0.
