### ISSUE TITLE
std::vector type visit failure

### ISSUE THREAD

**Issue by JSandusky** [mono/CppSharp#651]
##### Brief Description
OS: Windows (using binaries grabbed from appveyor build artifacts)

Probably expected but headers containing std::vector<T> are all failing to parse/generate. Case of failing source and error log below. Failure still occurs if only the member definitions in the class are left (after commenting out the accessor functions).

##### Used headers
One particular file: http://hastebin.com/sapazoxota.cpp
Alternative Link: https://gist.github.com/tritao/4a48519392375c332789c1901d70d703

Notables, "typedef std::vector<T> typeName;" and returning by reference/const-reference in all cases. NOCOPYDEF macro is not remarkable (used elsewhere) just a generic "prevent copy" define.

##### Used settings
Target: MSVC, C++11, generating C++/CLI

```
var options = driver.Options;
options.Quiet = false;
options.LibraryName = LibraryName;
options.SharedLibraryName = LibraryName + ".Native.dll";
options.LanguageVersion = CppSharp.Parser.LanguageVersion.CPlusPlus11;
options.GeneratorKind = cli ? CppSharp.Generators.GeneratorKind.CLI : CppSharp.Generators.GeneratorKind.CSharp;
options.GenerateSingleCSharpFile = true;
options.Headers.AddRange(Includes);
options.Libraries.AddRange(Libraries);
options.OutputDir = WriteDir;
options.GenerateLibraryNamespace = false;
options.DryRun = Dry;
```

##### Stack trace or incompilable generated code
```
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at CppSharp.Generators.CLI.CLITypePrinter.VisitTemplateParameterSubstitutionType(TemplateParameterSubstitutionType param, TypeQualifiers quals) in c:\projects\cppsharp\src\Generator\Generators\CLI\
CLITypePrinter.cs:line 288
   at CppSharp.AST.TemplateParameterSubstitutionType.Visit[T](ITypeVisitor`1 visitor, TypeQualifiers quals) in c:\projects\cppsharp\src\AST\Type.cs:line 756
   at CppSharp.Generators.CLI.CLITypePrinter.VisitPointerType(PointerType pointer, TypeQualifiers quals) in c:\projects\cppsharp\src\Generator\Generators\CLI\CLITypePrinter.cs:line 188
   at CppSharp.AST.PointerType.Visit[T](ITypeVisitor`1 visitor, TypeQualifiers quals) in c:\projects\cppsharp\src\AST\Type.cs:line 321
   at CppSharp.Generators.CLI.CLIGenerator.TypePrinterDelegate(Type type) in c:\projects\cppsharp\src\Generator\Generators\CLI\CLIGenerator.cs:line 50
   at CppSharp.AST.Type.ToString() in c:\projects\cppsharp\src\AST\Type.cs:line 31
   at CppSharp.AST.QualifiedType.ToString() in c:\projects\cppsharp\src\AST\Type.cs:line 75
   at CppSharp.Passes.DeclarationName.<UpdateName>b__1(Parameter p) in c:\projects\cppsharp\src\Generator\Passes\CheckDuplicatedNamesPass.cs:line 47
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at CppSharp.Passes.DeclarationName.UpdateName(Function function) in c:\projects\cppsharp\src\Generator\Passes\CheckDuplicatedNamesPass.cs:line 55
   at CppSharp.Passes.DeclarationName.UpdateName(Declaration decl) in c:\projects\cppsharp\src\Generator\Passes\CheckDuplicatedNamesPass.cs:line 26
   at CppSharp.Passes.CheckDuplicatedNamesPass.CheckDuplicate(Declaration decl) in c:\projects\cppsharp\src\Generator\Passes\CheckDuplicatedNamesPass.cs:line 215
   at CppSharp.Passes.CheckDuplicatedNamesPass.VisitMethodDecl(Method decl) in c:\projects\cppsharp\src\Generator\Passes\CheckDuplicatedNamesPass.cs:line 146
   at CppSharp.Passes.CheckDuplicatedNamesPass.VisitClassDecl(Class class) in c:\projects\cppsharp\src\Generator\Passes\CheckDuplicatedNamesPass.cs:line 162
   at CppSharp.AST.Class.Visit[T](IDeclVisitor`1 visitor) in c:\projects\cppsharp\src\AST\Class.cs:line 279
   at CppSharp.AST.AstVisitor.VisitTemplateSpecializationType(TemplateSpecializationType template, TypeQualifiers quals) in c:\projects\cppsharp\src\AST\ASTVisitor.cs:line 186
   at CppSharp.AST.TemplateSpecializationType.Visit[T](ITypeVisitor`1 visitor, TypeQualifiers quals) in c:\projects\cppsharp\src\AST\Type.cs:line 658
   at CppSharp.AST.AstVisitor.VisitTypedefDecl(TypedefDecl typedef) in c:\projects\cppsharp\src\AST\ASTVisitor.cs:line 346
   at CppSharp.AST.TypedefDecl.Visit[T](IDeclVisitor`1 visitor) in c:\projects\cppsharp\src\AST\Declaration.cs:line 372
   at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in c:\projects\cppsharp\src\AST\ASTVisitor.cs:line 429
   at CppSharp.AST.AstVisitor.VisitNamespace(Namespace namespace) in c:\projects\cppsharp\src\AST\ASTVisitor.cs:line 405
   at CppSharp.AST.Namespace.Visit[T](IDeclVisitor`1 visitor) in c:\projects\cppsharp\src\AST\Namespace.cs:line 457
   at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in c:\projects\cppsharp\src\AST\ASTVisitor.cs:line 440
   at CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(TranslationUnit unit) in c:\projects\cppsharp\src\Generator\Passes\Pass.cs:line 42
   at CppSharp.Passes.TranslationUnitPass.VisitLibrary(ASTContext context) in c:\projects\cppsharp\src\Generator\Passes\Pass.cs:line 26
   at CppSharp.Driver.<ProcessCode>b__5(TranslationUnitPass pass) in c:\projects\cppsharp\src\Generator\Driver.cs:line 323
   at CppSharp.PassBuilder`1.RunPasses(Action`1 action) in c:\projects\cppsharp\src\Generator\Passes\PassBuilder.cs:line 48
   at CppSharp.Driver.ProcessCode() in c:\projects\cppsharp\src\Generator\Driver.cs:line 318
   at CppSharp.ConsoleDriver.Run(ILibrary library) in c:\projects\cppsharp\src\Generator\Driver.cs:line 508
   at SharpBind.Program.Main(String[] args) in c:\dev\SprueKit\SharpBind\Program.cs:line 204
```

**Comment by ddobrev** [comment]
Your link only displays an empty dark screen to me. Could you please ensure it works or move the code somewhere else?

**Comment by tritao** [comment]
@ddobrev I can see it, I've mirrored it in https://gist.github.com/tritao/4a48519392375c332789c1901d70d703

**Comment by JSandusky** [comment]
Sorry about that, I assumed hastebin was sufficiently spartan that it'd work anywhere. Added tritao's mirror to the initial post as an alternative link.

Also, I failed to note that the failures occur when generating C++/CLI. 

C# generation appears to work (dumping Std.Vector<T> types) though I haven't tested if that _actually_ works when it comes time to compile.

If more information is required let me know.

---
Though honestly I'm not too concerned with the issue as exposing those vector's should probably be manually written as a full copy into/from a System.Array C++/CLI side, so I'll likely just #ifdef my way around them and manually write those function bindings (not a lot of std::vector's in the public interfaces of the code anyways).

**Comment by tritao** [comment]
@JSandusky C++/CLI has historically had an advantage for this use case and CppSharp has been able to wrap `std::vector` almost since the beginning of the project. In fact my initial use case was very similar to yours (a 3D engine). It's implemented as a type map and is implemented here, https://github.com/mono/CppSharp/blob/master/src/Generator/Types/Std/Stdlib.cs#L102.

That said, I haven't tested this in a while, so it's likely this support has regressed since we're lacking some test coverage in this area. The issue represented in the stack trace should be a simple one to fix, just thread through the type name in `CLITypePrinter.VisitTemplateParameterSubstitutionType` and hopefully that'd fix it.

Even though we now generate some code related to templates in C#, this is still a work-in-progress and not ready yet for full wrapping of `std::vector`. @ddobrev has been the one improving this area for C# this and I think he expects to get it fully done sooner rather than later.

**Comment by JSandusky** [comment]
@tritao, I was coming to that conclusion after I noticed I had other types that were dealing with std::vector without issue.

I've narrowed it down. The "IndexBuffer" typedef seems to be the trigger that causes things to go wrong:
`typedef std::vector<unsigned int> IndexBuffer;`

That typedef seems to mangle the handling of the "std::vector<unsigned int> indexBuffer_;" towards the bottom. Interesting the functions returning std::vector<unsigned int> don't create any problems and bind generate as expected. Just the presence of that indexBuffer_ declaration WITH the typedef causes the problem.

Replacing the typedef with a #define results in successful generation and everything is healthy in the generated code. That's easy harmless enough of a work-around.

**Comment by tritao** [comment]
Turns out we actually have some tests for `std::vector` in https://github.com/mono/CppSharp/blob/master/tests/StandardLib/StandardLib.Tests.cs.

I've pushed a small fix for the original issue, please check if it fixes your original issue since I could not come up with a test case, if not please re-open.

**Comment by JSandusky** [comment]
Confirmed. No longer errors and generated code checks out. Shockingly tiny change looking at the commit.

Thanks!

**Comment by polar** [comment]
I'm sorry I'm late on this, but is this test supposed to generate CSharp properties for fields and functions that return std::vector<...> ?

From what I get, it creates a gen/StandardLib/StandardLib.cs file that contains aside from the __Internal member class, it generates a TestVectors constructor and Dispose, and that is it.

**Comment by tritao** [comment]
@polar Did you enable generation of class templates in the generator options?

**Comment by polar** [comment]
I think I misspoke. I'm not looking to template. I'm wondering what I have to do to get
struct XXX {
   std::vector<int> foo;
}

to generate

public unsafe partial class XXX : IDisposable {
    public List<int> foo { get {}, set {} }
}

which it seems not to be doing for me. 
I'm using CppSharp/build/gmake/lib/Release_x64/CppSharp.CLI.exe.

**Comment by tritao** [comment]
Try `driver.Options.GenerateClassTemplates = true;`.

**Comment by polar** [comment]
That doesn't seem to work. I added it to CLI/Generator.cs and rebuilt CppSharp.CLI.exe. It gives me definitions for all integral type and and classes, but nothing for std::vector<int>. 
 
I've chased it down in the FieldToPropertyPass:41, VisitFieldDecl calls ASTUtils.CheckIgnoreField() and it returns false because basically, Field.isGenerated = false.

**Comment by polar** [comment]
I have a class that has the following
```
struct StopInfo {
   std::list<int> Hello;
};
```
I run the following (with the Verbose flag turned on):
mono ~/src/CppSharp/build/gmake/lib/Release_x64/CppSharp.CLI.exe -ax64 StopInfo.hpp

and in the output there is the following message:

```
Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
    Field 'StopInfo::Hello' was ignored due to ignored type '::std::list<int, ::std::allocator<int>>'
```
How can I get CppSharp not to ignore this type?

**Comment by tritao** [comment]
Hmm we seem to have a type map that ignores it for C++/CLI, see https://github.com/mono/CppSharp/blob/master/src/Generator/Types/Std/Stdlib.cs#L650.

However I assume you are using the C# backend so that is probably not it.

We also have some kind of hardcoded list of std types in the parser: https://github.com/mono/CppSharp/blob/17cc96bafd6abeb81d603aa5b907dc66f1547730/src/CppParser/Parser.cpp#L74

I am not sure if this is what's going on with your case, I guess not because the `std::list` type actually comes up in the passes, which suggests its not being ignored by the parser itself, but at a later stage.

@ddobrev Any idea what this could be?

**Comment by ddobrev** [comment]
@tritao it's normal to ignore it as the only templates we support at present are std::string and its prerequisites. @polar adding support for them is not immensely difficult but I'm too busy at present. Unless you can wait, you could either contribute it yourself or contact our support.

**Comment by polar** [comment]
Oh, okay, I was under the impression that this would work, I just didn't know what options to flip on. I'll have to do them by hand. I hope I can get that right.

**Comment by tritao** [comment]
@polar Try changing both of these to always return true:

```
bool Parser::IsSupported(const clang::NamedDecl* ND)
bool Parser::IsSupported(const clang::CXXMethodDecl* MD)
```

https://github.com/mono/CppSharp/blob/master/src/CppParser/Parser.cpp#L923-L930
