### ISSUE TITLE
Mapnik bindings - how to start?

### ISSUE THREAD

**Issue by rouen-sk** [mono/CppSharp#664]
Hi guys, there is this awesome c++ library for creating maps - mapnik. It is de facto standard in the business (openstreetmaps, mapbox..), but there is no .NET binding. (actually, there is: https://github.com/jbrwn/NET-Mapnik , but it is based on more than a year old mapnik and the author has no plan to keep it updated anymore). I would like to create .NET binding for it and CppSharp seems like the good way to do it. However, I am not c++ programmer at all, so I would really like some advice/help on how to start. 

Of course, I tried to apply the basic tutorial on it.

1.  I downloaded the latest Mapnik SDK release: http://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.11-x64-14.0.7z
2. Created new c# console application and added CssSharp as Nuget package.
3. Created MapnikLibrary class like this

```
class MapnikLibrary : ILibrary
    {
        public void Postprocess(Driver driver, ASTContext ctx)
        {
            
        }

        public void Preprocess(Driver driver, ASTContext ctx)
        {
            
        }

        public void Setup(Driver driver)
        {
            var options = driver.Options;
            options.GeneratorKind = CppSharp.Generators.GeneratorKind.CSharp;
            options.OutputDir = @"..\..\..\output\";
            options.Verbose = true;

            options.LibraryName = "Mapnik";
            options.addIncludeDirs(@"..\..\..\mapnik-sdk\include\");
            options.addLibraryDirs(@"..\..\..\mapnik-sdk\lib");

            options.LibraryFile = @"..\..\..\mapnik-sdk\lib\mapnik.dll";

            options.Headers.Add(@"..\..\..\mapnik-sdk\include\mapnik\params.hpp");
            options.Headers.Add(@"..\..\..\mapnik-sdk\include\mapnik\map.hpp");
                        

        }

        public void SetupPasses(Driver driver)
        {
            
        }
    }
```
4. Run `ConsoleDriver.Run(new MapnikLibrary());`

And of course, this didnt work :) 

```
Parsing libraries...
Indexing library symbols...
Parsing code...
ignoring nonexistent directory "lib\clang\3.9.0\include"
#include "..." search starts here:
#include <...> search starts here:
 ..\..\..\mapnik-sdk\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Windows Kits\8.1\include\shared
 C:\Program Files (x86)\Windows Kits\8.1\include\um
 C:\Program Files (x86)\Windows Kits\8.1\include\winrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt
End of search list.
Error parsing '..\..\..\mapnik-sdk\include\mapnik\params.hpp'
..\..\..\mapnik-sdk\include\mapnik/value_types.hpp(183,65): error: no type named 'string' in namespace 'std'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(74,42): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(76,42): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(79,43): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(81,43): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(85,44): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(87,44): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(91,41): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(93,41): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(97,51): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(99,51): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(103,49): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\params.hpp(105,49): error: explicit instantiation of undefined function template 'get'
ignoring nonexistent directory "lib\clang\3.9.0\include"
#include "..." search starts here:
#include <...> search starts here:
 ..\..\..\mapnik-sdk\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Windows Kits\8.1\include\shared
 C:\Program Files (x86)\Windows Kits\8.1\include\um
 C:\Program Files (x86)\Windows Kits\8.1\include\winrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt
End of search list.
Error parsing '..\..\..\mapnik-sdk\include\mapnik\map.hpp'
..\..\..\mapnik-sdk\include\mapnik/well_known_srs.hpp(47,1): warning: declaration does not declare anything
..\..\..\mapnik-sdk\include\..\..\..\mapnik-sdk\include\mapnik\map.hpp(508,1): warning: declaration does not declare anything
..\..\..\mapnik-sdk\include\mapnik/params.hpp(78,42): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(80,42): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(83,43): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(85,43): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(89,44): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(91,44): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(95,41): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(97,41): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(101,51): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(103,51): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(107,49): error: explicit instantiation of undefined function template 'get'
..\..\..\mapnik-sdk\include\mapnik/params.hpp(109,49): error: explicit instantiation of undefined function template 'get'
ignoring nonexistent directory "lib\clang\3.9.0\include"
#include "..." search starts here:
#include <...> search starts here:
 ..\..\..\mapnik-sdk\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Windows Kits\8.1\include\shared
 C:\Program Files (x86)\Windows Kits\8.1\include\um
 C:\Program Files (x86)\Windows Kits\8.1\include\winrt
 C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt
End of search list.
CppSharp has encountered an error while parsing code.
```

So - anyone willing to help? Frankly, I have no idea how to setup this correctly - for example, which headers to add, in what order, if the LibraryFile should be set to "mapnik.dll" in the first place; if the "ignoring nonexistent directory lib\clang\3.9.0\include" is a big deal or not... 
But I am always happy to learn.

**Comment by rouen-sk** [comment]
By the way, when I try to add all headers from `mapnik-sdk/include/mapnik` like this

`driver.Options.Headers.AddRange(Directory.EnumerateFiles(@"d:\Devel\MapnikWrapper\mapnik-sdk\include\mapnik", "*.hpp"));`

CppSharp fails like this:

```
{System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CppSharp.CppParser.ClangParser.ParseHeader(ParserOptions* )
   at CppSharp.Parser.ClangParser.ParseHeader(ParserOptions Opts)
   at CppSharp.ClangParser.ParseSourceFile(SourceFile file)
   at CppSharp.ClangParser.<ParseProject>b__11_0(SourceFile s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CppSharp.ClangParser.ParseProject(Project project, Boolean unityBuild)
   at CppSharp.Driver.ParseCode()
   at CppSharp.ConsoleDriver.Run(ILibrary library)
   at MapnikWrapper.Program.Main(String[] args) in D:\Devel\MapnikWrapper\MapnikWrapper\Program.cs:line 14
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()}
```

**Comment by tritao** [comment]
Hi, looks like some of the includes in `params.hpp` header  (`value_types.hpp`) rely on `std::string` which is only included later in the header which leads me to believe it is not meant to be included directly. I think you'll get the same error with a C++ compiler, nothing we can do about it.

Try removing it and starting only with `map.hpp`.

I took a quick look at the library and it seems to use some templates, with boost and C++ STL containers, which means you will need very good template support to get decent bindings or develop local workarounds.

What I recommend you do is to write a subset of the API you need in simple C++ (at least until we improve the template support in CppSharp which should take a few weeks). You can also ask the library developers to provide a simplified API with no dependencies on templates, that will help all the people who want to interop with the library for other languages.

I also glanced at NETMapnik, it's written with C++/CLI so it will only work with .NET on Windows.

**Comment by tritao** [comment]
About the AccessViolationException, I am looking into it. We've been making heavy core changes in the last few weeks and seems like we did not yet catch some regressions which this code is surfacing. I should have some fixes up later.

**Comment by rouen-sk** [comment]
@tritao thanks a lot for quick answer! As I said, I am not c++ programmer, so "develop local workarounds" and "write a subset of the API you need in simple C++" are not really options for me. Looks like I have to wait for you guys to improve template support in CppSharp. I can see you already done some work on this - let me say I am super impressed by activity of this project. I am really looking forward to use CppSharp to bring Mapnik to .NET world.

**Comment by ddobrev** [comment]
@rouen-sk @tritao has fixed 7 problem revealed by Mapnik but unfortunately this is all the time he, and I, have for now. However, In case you are not just an enthusiast but rather need Mapnik bindings for commercial purposes, you can always contact our support at https://github.com/mono/CppSharp#support .

**Comment by pizzaeater** [comment]
Hm, I have no access to `options.Verbose` and `options.LibraryFile` property, I cannot set it.

**Comment by rouen-sk** [comment]
@pizzaeater do not even try it. It is not possible to make working mapnik bindings with CppSharp at this time.

**Comment by pizzaeater** [comment]
I'm trying to make binding for another big library, just curious about `options.LibraryFile` property. I need to set path to ".a" file.

**Comment by tritao** [comment]
Those properties are in the `DriverOptions` class, you can see that they're still available: https://github.com/mono/CppSharp/blob/master/src/Generator/Options.cs#L85

Please open a new issue and paste some code and the compile errors and I will try to help.
