### ISSUE TITLE
Build Failure due to UnHandled exception in a test project

### ISSUE THREAD

**Issue by genuinelucifer** [mono/CppSharp#762]
##### Brief Description
Hi, I was building C++# from VS Developer command prompt but the build failed. The main reason seems to be a test project `CSharp`... I am pasting the part of the log which shows the stacktrace. Is it a known issue?

I've built LLVM with the correct `LLVM-commit` and `Clang-commit` following the instructions on `Building LLVM` doc. I built it myself as the download of pre-built binaries always failed...

OS: Windows

##### Used settings
Target: Visual Studio 2015

##### Stack trace or incompilable generated code
PreBuildEvent:
  "D:\repos\CppSharp\build\vs2015\lib\Release_x32\CSharp.Gen.exe"

  Generating bindings for CSharp (CSharp)
  Looking for tests in: D:\repos\CppSharp\tests\CSharp
  Parsed 'AnotherUnit.h'
  Parsed 'CSharp.h'
  Parsed 'CSharpTemplates.h'
      Duplicate operator implicit operator ignored

  Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
     at CppSharp.Generators.CodeGenerator.VisitTypeAliasDecl(TypeAlias typeAlias) in D:\repos\CppSharp\src\Generator\Ge
  nerators\CodeGenerator.cs:line 100
     at CppSharp.AST.TypeAlias.Visit[T](IDeclVisitor`1 visitor) in D:\repos\CppSharp\src\AST\Typedef.cs:line 33
     at CppSharp.Generators.CSharp.CSharpSources.VisitDeclContext(DeclarationContext context) in D:\repos\CppSharp\src\
  Generator\Generators\CSharp\CSharpSources.cs:line 226
     at CppSharp.Generators.CodeGenerator.VisitNamespace(Namespace namespace) in D:\repos\CppSharp\src\Generator\Genera
  tors\CodeGenerator.cs:line 125
     at CppSharp.Generators.CSharp.CSharpSources.VisitNamespace(Namespace namespace) in D:\repos\CppSharp\src\Generator
  \Generators\CSharp\CSharpSources.cs:line 209
     at CppSharp.AST.Namespace.Visit[T](IDeclVisitor`1 visitor) in D:\repos\CppSharp\src\AST\Namespace.cs:line 460
     at CppSharp.Generators.CSharp.CSharpSources.Process() in D:\repos\CppSharp\src\Generator\Generators\CSharp\CSharpS
  ources.cs:line 159
     at CppSharp.Generators.Generator.GenerateSingleTemplate(ICollection`1 outputs) in D:\repos\CppSharp\src\Generator\
  Generator.cs:line 123
     at CppSharp.Generators.Generator.Generate() in D:\repos\CppSharp\src\Generator\Generator.cs:line 78
     at CppSharp.Driver.GenerateCode() in D:\repos\CppSharp\src\Generator\Driver.cs:line 354
     at CppSharp.ConsoleDriver.Run(ILibrary library) in D:\repos\CppSharp\src\Generator\Driver.cs:line 516
     at CppSharp.Tests.CSharpTestsGenerator.Main(String[] args) in D:\repos\CppSharp\tests\CSharp\CSharp.cs:line 176
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: The command ""D
:\repos\CppSharp\build\vs2015\lib\Release_x32\CSharp.Gen.exe"" exited with code -532462766. [D:\repos\CppSharp\tests\CS
harp\CSharp.CSharp.csproj]
Done Building Project "D:\repos\CppSharp\tests\CSharp\CSharp.CSharp.csproj" (default targets) -- FAILED.

Done Building Project "D:\repos\CppSharp\build\vs2015\..\..\tests\CSharp\CSharp.CSharp.csproj.metaproj" (default target
s) -- FAILED.

**Comment by ddobrev** [comment]
@genuinelucifer @tritao fixed this one yesterday, please pull the latest code and it's going to work.

**Comment by genuinelucifer** [comment]
Thanks @ddobrev It worked!
