### ISSUE TITLE
"Query API not registered", cannot set verbose, wrong version of VS detected?

### ISSUE THREAD

**Issue by debrowne** [mono/CppSharp#826]
##### Brief Description

I'm having a few problems running a generator after building. It builds fine, but the application appears to be ignoring includes (or something like that) and so it's reporting some errors.

The application console reads:
> The query API is not registered. Assuming no instances are installed.
> The query API is not registered. Assuming no instances are installed.
> The query API is not registered. Assuming no instances are installed.
> Parsing libraries...
> A file from 'C:/Users/David/Documents/Visual Studio 2015/Projects/TestingCpp/x64/Release/TestingCpp.lib' was not found
> Parsing code...
> Error parsing C:/Users/David/Documents/Visual Studio 2015/Projects/TestingCpp/TestingCpp/TestingCpp.h'
> C:/Users/David/Documents/Visual Studio 2015/Projects/TestingCpp/include/kfr/dft/../base/min_max.hpp(41, 67) : error: no matching function for call to '_mm_min_ps'
> 

That last error is repeated several times for a number of functions that are defined in the headers xmmintrin.h and eminntrin.h in .../Microsoft Visual Studio 14.0/VC/include.

It's my understanding that this directory is automatically included in driver options (seeing as it has all the standard library stuff), but it makes no difference if I explicitly include it (i.e. the code below gives the same result regardless of whether this directory is explicitly included).

I've looked briefly at the source code, and it seems that the "Query API" message is returned when CppSharp tries to get the VS toolchain, so I'm wondering if it's detecting and looking for the wrong version? I've tried telling it which version of VS to look for with driver.Options.VsVersion = VisualStudioVersion.VS2015 but that doesn't make any difference.

Another issue I'm having is that I can't set verbose. I can build with both driver.ParserOptions.Verbose and driver.Options.Verbose set to true and the application still won't give verbose output.

OS: Windows 10
VS 2015
CppSharp: 0.8.10 x64 (from NuGet)

Source code:

```
using System;
using CppSharp;
using CppSharp.AST;
using System.IO;


namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            ConsoleDriver.Run(new TestingCpp());
            Console.ReadLine();
        }
    }

    class TestingCpp : ILibrary
    {
        public void Setup(Driver driver) {
            driver.ParserOptions.Verbose = true;
            var options = driver.Options;
            options.VsVersion = VisualStudioVersion.VS2015;
            options.Verbose = true;
            var module = options.AddModule("TestingCpp");
            module.Headers.Add(@"C:\Users\David\Documents\Visual Studio 2015\Projects\TestingCpp\TestingCpp\TestingCpp.h");
            module.Libraries.Add(@"C:\Users\David\Documents\Visual Studio 2015\Projects\TestingCpp\x64\Release\TestingCpp.lib");
            module.IncludeDirs.Add(@"C:\Users\David\Documents\Visual Studio 2015\Projects\TestingCpp\include");
            module.IncludeDirs.Add(@"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include");
        }

        public void SetupPasses(Driver driver) { }

        public void Preprocess(Driver driver, ASTContext ctx) { }

        public void Postprocess(Driver driver, ASTContext ctx) { }
    }
}

```

**Comment by ddobrev** [comment]
Hello @debrowne . As you can see in our sample at https://github.com/mono/CppSharp/blob/master/docs/GeneratingBindings.md , you must not add libraries and headers with a path but rather with just a file name. All directories which contain your headers and libraries must be added to IncludeDirs/LibraryDirs instead.

**Comment by tritao** [comment]
@realvictorprm If you have some time, it would be nice to improve the VS lookup error reporting here. The repeated `The query API is not registered. Assuming no instances are installed.` provide no context into what the issue or not might be.

**Comment by realvictorprm** [comment]
@tritao I agree. I hope it isn't a bug in the MSVCToolchain.cs

**Comment by debrowne** [comment]
@ddovrev . Thanks for the reply, I see where I went wrong.

I've replaced the code with:

       public void Setup(Driver driver) {
            driver.Options.VsVersion = VisualStudioVersion.VS2015;
            var options = driver.Options;
            options.Verbose = true;
            driver.ParserOptions.Verbose = true;

            var module = options.AddModule("TestingCppKFR");
            module.IncludeDirs.Add(@"C:\Users\David\Documents\Visual Studio 2015\Projects\TestingCpp\TestingCpp");
            module.IncludeDirs.Add(@"C:\Users\David\Documents\Visual Studio 2015\Projects\TestingCpp\include");
            module.Headers.Add("TestingCpp.h");
            module.LibraryDirs.Add(@"C:\Users\David\Documents\Visual Studio 2015\Projects\TestingCpp\x64\Debug");
            module.Libraries.Add("TestingCpp.lib");

        }

The messages regarding the files from the headers/libraries not being found no longer shows up, but I still get the messages about the missing function calls and the parsing error.

I've used the same syntax to compile a functioning cppsharp generator for a nearly empty library, so I believe it's correct.

The library I'm trying to create the csharp interface for was compiled with the latest clang (actually clang-cl in VS) and has no problem locating these function calls

**Comment by realvictorprm** [comment]
@debrowne Try adding the clang headers instead of the MSVC toolchain if the headers you try to create bindings for are incompatible with MSVC.

**Comment by debrowne** [comment]
@realvictorprm I had that idea as well.

I've tried adding the header directories as includes to the module, to the Driver.ParserOptions and to the DriverParserOptions system directories. Either of the latter two approaches manage to parse the library and header, but then I get a NullReferenceException in CppSharp.AST when trying to process. The stacktrace is:

System.NullReferenceException was unhandled
HResult=-2147467261
Message=Object reference not set to an instance of an object.
Source=CppSharp.AST
StackTrace:
- at CppSharp.AST.AstVisitor.VisitVariableDecl(Variable variable)

- at CppSharp.AST.Variable.Visit[T](IDeclVisitor`1 visitor)

- at CppSharp.AST.AstVisitor.VisitVarTemplateDecl(VarTemplate template)

- at CppSharp.AST.VarTemplate.Visit[T](IDeclVisitor`1 visitor)

- at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context)

- at CppSharp.AST.AstVisitor.VisitNamespace(Namespace namespace)

- at CppSharp.AST.Namespace.Visit[T](IDeclVisitor`1 visitor)

- at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context)

- at CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(TranslationUnit unit)

- at CppSharp.Passes.TranslationUnitPass.VisitASTContext(ASTContext context)

- at CppSharp.Passes.ResolveIncompleteDeclsPass.VisitASTContext(ASTContext c)

- at CppSharp.Generators.BindingContext.<RunPasses>b__37_0(TranslationUnitPass pass)

- at CppSharp.PassBuilder`1.RunPasses(Action`1 action)

- at CppSharp.Generators.BindingContext.RunPasses()

- at CppSharp.Driver.ProcessCode()

- at CppSharp.ConsoleDriver.Run(ILibrary library)

- at test.Program.Main(String[] args) in C:\Users\David\documents\visual studio 2015\Projects\CppCsharp_interface\CppCsharp_interface\Program.cs:line 13

I'm still getting the "query API not registered" message, but I'm not sure that's significant. I no longer get any output regarding missing function definitions. I might try to rewrite the header using simpler types.

**Comment by tritao** [comment]
If possible, send us a reproducible test case so we can get this one fixed.

You can safely ignore the `query API not registered` message, it's just because you do not have VS 2017 installed, we've fixed this one in master.

**Comment by tritao** [comment]
@debrowne Is this still an issue? Could you get us a reproduction?

**Comment by tritao** [comment]
@debrowne Ping, did you ever get this sorted out?
